### ISSUE TITLE
Inspect step fails, because of missing ENV

### ISSUE THREAD

**Issue by nexeck** [grafana/run-k6-action#21]
https://github.com/grafana/run-k6-action/blob/575942d000c76d66708b9232d2d506153df6dc8f/src/k6helper.ts#L29

Is there a reason, why ENV isn't pushed into the k6 inspect command?
This makes it fail for aws tests

`ERRO[0000] Error: invalid AWS region; reason: expected a valid AWS region name (e.g. "us-east-1"), got `undefined`
        at apply (native)
        at webpack://k6-jslib-aws/./src/internal/endpoint.ts:4:21(12)
        at r (webpack://k6-jslib-aws/./src/internal/endpoint.ts:4:21(12))
        at construct (native)
        at T (webpack://k6-jslib-aws/./src/internal/endpoint.ts:4:21(24))
        at t (webpack://k6-jslib-aws/./src/internal/config.ts:177:33(14))
        at e (webpack://k6-jslib-aws/./src/internal/config.ts:82:18(58))
        at value (webpack://k6-jslib-aws/./src/internal/config.ts:65:15(24))
        at file:///Users/xxxx/code/xxxxx/test/src/xxxxx--smoke-test.js:8:18(46)  hint="script exception"
`

Part of the testfile which fails:

`import {AWSConfig, Endpoint, SignatureV4,} from 'https://jslib.k6.io/aws/0.12.3/signature.js';

const awsConfig = AWSConfig.fromEnvironment()`

The only missing part seems to be:
https://github.com/grafana/run-k6-action/blob/main/src/index.ts#L190
And adding the flag: --include-system-env-vars

**Comment by TuanNguyenEPI** [comment]
I also got the same issue, but with k6 cloud command. Looking forward to the solution.

**Comment by dhaakchg** [comment]
Any chance this PR can get merged soon so this action is usable again?

**Comment by dhaakchg** [comment]
`Warning: Unexpected input(s) 'inspect-flags', valid inputs are ['github-token', 'path', 'parallel', 'fail-fast', 'flags', 'cloud-run-locally', 'cloud-comment-on-pr', 'only-verify-scripts', 'debug']`

Need to create a new release now this is merged?

**Comment by DefCon-007** [comment]
Closing the issue as `inspect-flags` is now supported - https://github.com/grafana/run-k6-action#:~:text=10%20%2D%2Dduration%2020s-,inspect%2Dflags,-string
